force_update:
  name: "PT: Forçar atualização Edenred Portugal // EN: Edenred Portugal Force Update"
  description: "PT: Força a atualização dos dados Edenred Portugal // EN: Forces sensor update for Edenred Portugal"
  fields: {}
