name: Validate Integration

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"   # Corre todos os dias à meia-noite (UTC)

jobs:

  hacs_validation:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run HACS Action
        uses: hacs/action@22.5.0

  hassfest_validation:
    name: Hassfest Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Hassfest
        uses: home-assistant/actions/hassfest@master
